/* Adding LICENSE_ADMIN role */
insert into ROLES (UUID, CREATED_DATE, DELETED, IS_DISABLED, IS_OUT_OF_SYNC, LOCKED, MODIFIED_DATE, VERSION_NUMBER, DISPLAY_NAME, NAME, TYPE)
VALUES ('6268FD06A04F4C62BB911D7541B2CFA5',CURRENT_TIMESTAMP,null,false,false,true,CURRENT_TIMESTAMP,1,'License Administrator','LICENSE_ADMIN', 'PROVIDER');