/* Create table for Abstract Group objects */
CREATE TABLE ABSTRACT_GROUP (
  UUID varchar(32) not null unique,
  CREATED_DATE timestamp,
  DELETED varchar(32),
  IS_DISABLED NUMBER(0,1),
  IS_OUT_OF_SYNC NUMBER(0,1),
  LOCKED NUMBER(0,1),
  MODIFIED_DATE timestamp,
  VERSION_NUMBER NUMBER(19),
  DISPLAY_NAME varchar(1024),
  NAME varchar(1024),
  ENTITY_TAG VARCHAR(32),
  GROUP_INFO VARCHAR(1024),
  ORGANIZATION VARCHAR(32),
  primary key (UUID)
);

CREATE TABLE ABSTRACT_GROUP_METADATA (
  UUID varchar(32),
  FIELD_KEY VARCHAR(255),
  FIELD_VALUE VARCHAR (255),
  PRIMARY KEY (UUID, FIELD_KEY, FIELD_VALUE)
)