/* Adding SEARCH role */
insert into ROLES (UUID, CREATED_DATE, DELETED, IS_DISABLED, IS_OUT_OF_SYNC, LOCKED, MODIFIED_DATE, VERSION_NUMBER, DISPLAY_NAME, NAME, TYPE)
VALUES ('6268FD06A0123C62BB911D7541B2CFA7',CURRENT_TIMESTAMP,null,false,false,true,CURRENT_TIMESTAMP,1,'Search','SEARCH', 'PROVIDER');